#!/usr/bin/python3

from sys import argv

if len(argv) != 2:
   exit()

def factorize(value):
   q = 2

   if value < 2:
      return
   
   while value % q:
      q += 1
   p = value / q
   print("{:.0f}={:.0f}*{:.0f}".format(value, p, q))

try:
   my_file = open(argv[1], "r")

   if my_file.mode == 'r':
      line = my_file.readline()
      while line != "":
         n = int(line.split('\n')[0])
         factorize(n)
         line = my_file.readline()
except:
   pass
